# Generated by Django 3.1 on 2021-08-08 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 0, 28, 5, 149501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 0, 28, 5, 149501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 0, 28, 5, 149501, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 8, 0, 28, 5, 150308)),
        ),
    ]
