# Generated by Django 3.1 on 2021-07-12 03:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 12, 3, 58, 7, 626637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 12, 3, 58, 7, 626637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='shop/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 7, 12, 3, 58, 7, 627571)),
        ),
    ]
