# Generated by Django 3.1 on 2021-08-08 02:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210808_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='price',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 2, 44, 36, 891875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 2, 44, 36, 891875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 2, 44, 36, 891875, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 8, 2, 44, 36, 892949)),
        ),
    ]
