# Generated by Django 3.1 on 2021-08-08 08:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210808_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 8, 42, 54, 574306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 8, 42, 54, 574306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 8, 8, 42, 54, 574306, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(verbose_name=datetime.datetime(2021, 8, 8, 8, 42, 54, 575079)),
        ),
    ]
